### ISSUE TITLE
Misordered inds in Cartographer.expand

### ISSUE THREAD

**Issue by zhafen** [nathimel/sciterra#3]
I wanted to use the sorting logic in expand, so I refactored it out. In the process I discovered that it is highly likely that previously we were expanding based on the publications that were *least* similar.

This is fixed and tested in [this new branch](https://github.com/zhafen/sciterra/tree/ml_exploration), which will presumably be merged later. However, this warrants rerunning the full dataset... If we can use the existing data to validate that the order of expansion was correct we could avoid that.

**Comment by nathimel** [comment]
Yes, you appear to be right. Thanks for raising this issue!

For posterity, problem appears to be that the current implementation

`np.argsort(cospsi_matrix)[::-1][0]`

gives the reversed version of the following, which is equivalent to correction you implemented

`np.argsort(cospsi_matrix)[-1][::-1]`

I will re-run/rebuild our dataset 🫠

In the meantime, feel free to open a PR with the refactor!

**Comment by nathimel** [comment]
This same bug is present in the topography module: how we sort cosine similarities in order to compute smoothing length: https://github.com/nathimel/sciterra/blob/main/src/sciterra/mapping/topography.py#L46

I will implement the fix asap.

**Comment by zhafen** [comment]
Thanks, @nathimel !

**Comment by nathimel** [comment]
False alarm: the array `cospsi` on that line is a 1D array, so reverse sorting as 

```python
    cospsi_max = np.sort(cospsi)[::-1][kernel_size - 1]
```
correctly sorts the cosine similaries from greatest to least, and then indexing [kernel_size - 1] correctly retrieves the least similar value.
